[package]
name = "anchor-dockerfile"
version = "0.1.0"
authors = ["Fahmi Akbar Wildana <f.a.wildana@gmail.com>"]
edition = "2018"

[[bin]]
name = "anchor"
path = "src/main.rs"

[dependencies]
pulldown-cmark = { version = "0.7", default-features = false, features = ["simd"] }
